---
# License information (required)
license: 'github.com/msncakma'

# Database configuration
database:
  type: 'sqlite' # 'sqlite' or 'mysql'
  sqlite:
    # SQLite database file (relative to plugin data folder)
    filename: 'reports.db'
  mysql:
    host: 'localhost'
    port: 3306
    database: 'msnreports'
    username: 'admin'
    password: 'catsAreGreat'
    # Connection pool settings
    pool-size: 10
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000

# Security Settings
# IMPORTANT: Change this key to a secure random string!
encryption-key: 'change-this-to-a-secure-random-string-min-32-chars'

# Discord webhook configuration
discord:
  enabled: true
  webhooks:
    # Main webhook for bug reports
    # Set enabled to false if you don't want to use this webhook
    # Example URL: https://discord.com/api/webhooks/123456789/abcdefghijklmnop
    reports:
      enabled: false  # Change to true and add URL below when ready
      url: ''
    # Webhook for admin status changes
    admin-changes:
      enabled: false  # Change to true and add URL below when ready
      url: ''
    # Webhook for comments/notes added by admins
    admin-notes:
      enabled: false  # Change to true and add URL below when ready
      url: ''
    # Webhook for bug status changes
    status-changes:
      enabled: false  # Change to true and add URL below when ready
      url: ''

# Update notification settings
# The plugin automatically detects its version from plugin.yml
# It checks GitHub releases at: https://github.com/msncakma/msnReports/releases/latest
# No manual version configuration is needed
update-notifications:
  enabled: true
  check-on-startup: true
  notify-admins: true
  permission: 'msnreports.admin.notify'

# Admin notification settings
admin-notifications:
  enabled: true
  on-login: true
  permission: 'msnreports.notify'
